eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka
spring:
  application:
    name: eureka-client-goods
server:
  port: 8183
ribbon:
  eureka:
    enabled: true
env: test
branch: test
